default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>


development:
  primary:
    <<: *default
    database: search_term_development
  queue:
    <<: *default
    database: search_term_development
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/search_term_development_cable
    migrations_paths: db/cable_migrate
    
test:
  <<: *default
  database: search_term_test
  queue:
    <<: *default
    database: search_term_test
    migrations_paths: db/queue_migrate

production:
  primary: &primary_production
    <<: *default
    database: search_term_production
  queue:
    <<: *primary_production
    database: search_term_production
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/search_term_production_cable
    migrations_paths: db/cable_migrate