default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  port: <%= ENV["DB_PORT"] %>

development:
  primary:
    <<: *default
    database: search_term_development
  queue:
    <<: *default
    database: search_term_development
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: search_term_test
  queue:
    <<: *default
    database: search_term_test
    migrations_paths: db/queue_migrate

production:
  primary: &primary_production
    <<: *default
    database: search_term
  queue:
    <<: *primary_production
    database: search_term
    migrations_paths: db/queue_migrate