default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>


development:
  <<: *default
  database: search_term_development


test:
  <<: *default
  database: search_term_test

production:
  <<: *default
  database: search_term_production